spring:
  #profiles:
    #active: dev
  application:
    name: catalog-service
  config:
    import: "configserver:http://localhost:8888"

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics

server:
    port: 9001
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s

